export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const PRODUCTS_FETCHED = "PRODUCTS_FETCHED"
export const PRODUCTS_FAILED = "PRODUCTS_FAILED"